version: '3'

services:
  php:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    volumes:
      - ./:/app

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - php
  
  db:
    container_name: pi_mysql
    image: mysql
    volumes:
      - .docker/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GerenciamentoFinanceiro
    ports:
      - "3307:3306"

  phpmyadmin-api-GerenciamentoFinanceiro:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "9900:80"